
services:
  nginx:
    image: nginx:latest
    ports:
     - 80:80
    volumes:
      - ./:/usr/share/nginx/html
      - ./server/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
  php-fpm:
    # install PDO extension
    build: .
    volumes:
     - ./:/usr/share/nginx/html
    restart: unless-stopped
  database:
    container_name: miami-shoes-db
    image: mariadb
    ports:
     - "3306"
    environment:
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASS}
      - MARIADB_ROOT_PASSWORD=${DB_PASS}
      - MARIADB_DATABASE=${DB_NAME}
    volumes:
     - miami-db:/var/lib/mysql
     # include DB backup in container
     - ./database/db_backup.sql:/var/lib/mysql/backup
    restart: unless-stopped
volumes:
  miami-db: