<?php

// connect to DB
require __DIR__ . '/../dbconnect.php';

// get all product IDs
$products = $db->queryAndFetch('SELECT prod_id FROM products WHERE prod_id > 90');


// create csv file
$file = fopen("stock.txt", "w");

// write header row
fwrite($file, "sku,prod_id,size\n");

// generate sku for each size
foreach($products as $product => $field) {
  $size = 7;
  while ($size <= 14) {
    fwrite($file, "," . $field['prod_id'] . "," . $size . "\n"); // empty SKU field, auto-generated by DB
    $size += 0.5;
  }
}

fclose($file);

$db = null;

?>