CREATE TABLE orders (
	order_id VARCHAR(100) PRIMARY KEY,
    order_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dlvr_date DATETIME NOT NULL,
    cust_email VARCHAR(100) NOT NULL,
    cust_phone VARCHAR(10),
    cust_ext TINYINT,
    cust_first VARCHAR(100) NOT NULL,
    cust_last VARCHAR(100) NOT NULL,
    card_type VARCHAR(100),
    card_last4 TINYINT,
    bill_comp VARCHAR(100),
    bill_street VARCHAR(100),
    bill_street2 VARCHAR(100),
    bill_city VARCHAR(100),
    bill_state VARCHAR(100),
    bill_zip VARCHAR(100),
    ship_comp VARCHAR(100),
    ship_street VARCHAR(100),
    ship_street2 VARCHAR(100),
    ship_city VARCHAR(100),
    ship_state VARCHAR(100),
    ship_zip VARCHAR(100),
    ship_type VARCHAR(100),
    dlvr_instr VARCHAR(255),
    ordr_subtotal DECIMAL(7, 2) NOT NULL,
	ship_cost DECIMAL(7, 2) NOT NULL,
    ordr_taxes DECIMAL(7, 2) NOT NULL
);